{% set pyproject = load_file_data('pyproject.toml') %}
{% set version = pyproject.get('project', {}).get('version') %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: alinea.caribu
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script_env:
    - CMAKE_GEN=MinGW Makefiles # [win]
    - CMAKE_GENERATOR=MinGW Makefiles # [win]
    - CXX=g++ # [win]
    - CC=gcc # [win]
    - cxx_compiler=g++ # [win]
    - c_compiler=gcc # [win]
  script:
    - {{PYTHON}} -m pip install . -vv

requirements:
  host:
    - python x.x
    - setuptools
    - scikit-build-core
  build:
    - python {{PY_VER}}
    - {{ compiler('c') }}   
    - {{ compiler('cxx') }} 
    - m2w64-toolchain   # [win]
    - cmake
    - make
    - ninja
  run:
    - python x.x
    - path              # path.py is outdated
    - openalea.plantgl
    - openalea.mtg

test:
  requires:
    - pytest
  imports:
    - alinea.caribu
  source_files:
    - test/*.py
  commands:
   - pytest -v

about:
  home: https://openalea.readthedocs.io/
  summary: Eco-physiological model of light interception by plants.

