package:
  name: alinea.caribu
  version: "8.1.5"

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: 
    - {{ compiler('c') }} -v
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python x.x
    - setuptools
    - openalea.deploy
  build:
    - python x.x
    - {{ compiler('c') }}   
    - {{ compiler('cxx') }} 
    - m2w64-toolchain   # [win]
    - openalea.deploy
    - openalea.sconsx
  run:
    - python x.x
    - path              # path.py is outdated
    - openalea.plantgl
    - openalea.mtg

test:
  requires:
    - pytest
  imports:
    - alinea.caribu
  source_files:
    - test/*.py
  commands:
    - pytest -v

about:
  home: https://github.com/openalea-incubator/caribu
  summary: Eco-physiological model of light interception by plants.

