{% set data = load_setup_py_data() %}

package:
  name: alinea.caribu
  version: {{ data.get('version') }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 2
  script: python setup.py install #--single-version-externally-managed --record=record.txt

requirements:
  host:
    - python {{PY_VER}}
    - setuptools
    - openalea.deploy
    - m2w64-toolchain   [win]
  build:
    - {{ compiler('c') }}   # [unix]
    - {{ compiler('cxx') }} # [unix]
    - openalea.sconsx
  run:
    - openalea.deploy
    - path              # path.py is outdated
    - openalea.plantgl
    - openalea.mtg

test:
  requires:
    - pytest
  imports:
    - alinea.caribu
  source_files:
    - test/*.py
  commands:
   - pytest -v

about:
  home: {{ data.get('url') }}
  summary: Eco-physiological model of light interception by plants.

