{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set description = pyproject.get('project', {}).get('description') %}
{% set home = pyproject.get('project', {}).get('urls').get('Homepage') %}

package:
  name: {{ pyproject["project"]["name"] }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  script_env:
    - CMAKE_GEN=MinGW Makefiles # [win]
    - CMAKE_GENERATOR=MinGW Makefiles # [win]
    - CXX=g++ # [win]
    - CC=gcc # [win]
    - cxx_compiler=g++ # [win]
    - c_compiler=gcc # [win]
  script:
    - {{PYTHON}} -m pip install . -vv

requirements:
  host:
    - python x.x
    - setuptools-scm
    - scikit-build-core
  build:
    - python {{PY_VER}}
    - {{ compiler('c') }}   
    - {{ compiler('cxx') }} 
    - m2w64-toolchain   # [win]
    - m2w64-toolchain_win-64   # [win]
    - cmake
    - make
    - ninja
  run:
    - python x.x
    - path              # path.py is outdated
    - openalea.plantgl
    - openalea.mtg

test:
  requires:
    - pytest
  imports:
    - {{ pyproject["project"]["name"] }}
  source_files:
    - test/*.py
  commands:
   - pytest -v

about:
  home: {{ home }}
  description: {{ description }}
  summary: {{ description }}
  license: CeCILL_C