package:
  name: alinea.caribu
  version: 7.0.4

source:
  path: ..

about:
  home: http://openalea.gforge.inria.fr
  summary: Eco-physiological model of light interception by plants.


build:
  preserve_egg_dir: True
  number: 1

requirements:
  build:
    - {{ compiler('c') }}   # [unix]
    - {{ compiler('cxx') }} # [unix]
    - mingw   [win]
  host:
    - python {{PY_VER}}
    - setuptools
    #- openalea.deploy
    - openalea.sconsx
  run:
    - python {{PY_VER}}
    #- openalea.deploy
    - path.py
    - numpy
    - ipython
test:
  requires:
    - nose
    - openalea.plantgl
    - openalea.mtg
  imports:
    - alinea.caribu
  source_files:
    - test/test_*.py
  commands:
   - nosetests -v

