{% set pyproject = load_file_data('pyproject.toml') %}
{% set description = pyproject.get('project', {}).get('description') %}
{% set home = pyproject.get('project', {}).get('urls').get('Homepage') %}


package:
  name: alinea.caribu
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  script_env:
    - CMAKE_GEN=MinGW Makefiles # [win]
    - CMAKE_GENERATOR=MinGW Makefiles # [win]
    - CXX=g++ # [win]
    - CC=gcc # [win]
    - cxx_compiler=g++ # [win]
    - c_compiler=gcc # [win]
  script:
    - PREFIX={{ PREFIX }} {{PYTHON}} -m pip install --prefix={{ PREFIX }} . -vv

requirements:
  host:
    - python
    - scikit-build-core
    - cmake
    - make
    - ninja
  build:
    - {{ compiler('c') }}   
    - {{ compiler('cxx') }}
    - m2w64-toolchain   # [win]
    - m2w64-toolchain_win-64   # [win]
  run:
    - python
    - path              # path.py is outdated
    - openalea.plantgl
    - openalea.mtg

test:
  requires:
    - pytest
  imports:
    - alinea.caribu
  source_files:
    - test/*.py
  commands:
   - pytest -v

about:
  home: {{ home }}
  description: {{ description }}
  summary: {{ description }}
  license: CeCILL_C