{% set data = load_setup_py_data() %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: alinea.caribu
  version: {{ data.get('version') }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: 
    - {{PYTHON}} setup.py install

requirements:
  host:
    - python x.x
    - setuptools
    - openalea.deploy
  build:
    - python {{PY_VER}}
    - {{ compiler('c') }}   # [unix]
    - {{ compiler('cxx') }} # [unix]
    - m2w64-toolchain   # [win]
    - openalea.deploy
    - openalea.sconsx
  run:
    - python x.x
    - path              # path.py is outdated
    - openalea.plantgl
    - openalea.mtg

test:
  #requires:
  #  - pytest
  imports:
    - alinea.caribu
  #source_files:
  #  - test/*.py
  #commands:
  # - pytest -v

about:
  home: {{ data.get('url') }}
  summary: Eco-physiological model of light interception by plants.

