name: caribu
channels:
  - openalea3
  - conda-forge

dependencies:
  - python
  - sphinx_rtd_theme
  - alinea.caribu
  - mock
  - openalea.plantgl
  - openalea.core
  - openalea.mtg
  - sphinxcontrib-napoleon
